### ISSUE TITLE
[Help Wanted] Cannot find boto for ansible ec2 module.

### ISSUE THREAD

**Issue by cindyteng** [ansible-community/toolset#145]
Hello.
I am uing aws ec2 instance as my delegated driver for molecule testing.
I made modifcation to requirements.txt to handle this module.
But I am encountering this error upon running "molecule create".

root@0ede0570888f:/usr/local/ansible_role_bigfix# molecule create
INFO     default scenario test matrix: dependency, create, prepare
INFO     Performing prerun...
WARNING  Computed fully qualified role name of Deltek.ansible_role_bigfix does not follow current galaxy requirements.
Please edit meta/main.yml and assure we can correctly determine full role name:

galaxy_info:
role_name: my_name  # if absent directory name hosting role is used instead
namespace: my_galaxy_namespace  # if absent, author is used instead

Namespace: https://galaxy.ansible.com/docs/contributing/namespaces.html#galaxy-namespace-limitations
Role: https://galaxy.ansible.com/docs/contributing/creating_role.html#role-names

As an alternative, you can add 'role-name' to either skip_list or warn_list.

INFO     Using /root/.cache/ansible-lint/f5fbd7/roles/Deltek.ansible_role_bigfix symlink to current repository in order to enable Ansible to find the role using its expected full name.
INFO     Added ANSIBLE_ROLES_PATH=~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/root/.cache/ansible-lint/f5fbd7/roles
INFO     Running default > dependency
WARNING  Skipping, missing the requirements file.
WARNING  Skipping, missing the requirements file.
INFO     Running default > create

PLAY [Create Instance for Test] ************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Create Inventory File] ***************************************************
changed: [localhost]

TASK [Create Instance File] ****************************************************
changed: [localhost]

**TASK [Create EC2 Instance for Test] ********************************************
fatal: [localhost]: FAILED! => changed=false
  msg: boto required for this module**

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

CRITICAL Ansible return code was 2, command was: ansible-playbook --inventory /root/.cache/molecule/ansible_role_bigfix/default/inventory --skip-tags molecule-notest,notest /usr/local/ansible_role_bigfix/molecule/default/create.yml

The changes made in requirements.txt:
binaryornot==0.4.4
**boto
boto3
botocore**
bracex==2.1.1

Then I execute docker build command to create an image: (console logs)
[+] Building 441.3s (10/10) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for quay.io/pycontribs/python:3.8-slim-buster                                         1.3s
 => [internal] load build context                                                                                  0.0s
 => => transferring context: 1.91kB                                                                                0.0s
 => CACHED [toolset-builder 1/3] FROM quay.io/pycontribs/python:3.8-slim-buster@sha256:3bc519ca3214d463ac521f8382  0.0s
 => [toolset-builder 2/3] COPY requirements.txt /tmp/requirements.txt                                              0.0s
 => [toolset-builder 3/3] RUN apt-get update && apt-get install -y git gcc gnupg rsync ssh libyaml-dev  && pyth  224.2s
 => [stage-1 2/3] COPY --from=toolset-builder /opt/toolset /opt/toolset                                            4.0s
 => [stage-1 3/3] RUN apt-get update && apt-get install -y --no-install-recommends curl git gnupg docker.io &&   202.5s
 => exporting to image                                                                                             5.5s
 => => exporting layers                                                                                            5.5s
 => => writing image sha256:c2c079ed41b1b78668054f8f60ae13678583d78189406664b8029ac7fbb4f657                       0.0s
 => => naming to docker.io/cindyteng/molecule_cm                                                                   0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them

To verify if boto is installed, I tried to run pip list:
root@0ede0570888f:/usr/local/ansible_role_bigfix# pip list
Package               Version
--------------------- ---------
ansible               4.0.0
ansible-core          2.11.1
ansible-lint          5.0.12
appdirs               1.4.4
arrow                 1.1.0
bcrypt                3.2.0
binaryornot           0.4.4
**boto                  2.49.0
boto3                 1.17.105
botocore              1.20.105**
bracex                2.1.1
Cerberus              1.3.2

Here are some information:
root@a6f1dd3f62f7:/usr/local/ansible_role_bigfix# which python
/opt/toolset/bin/python
root@a6f1dd3f62f7:/usr/local/ansible_role_bigfix# python --version
Python 3.8.11
root@a6f1dd3f62f7:/usr/local/ansible_role_bigfix# molecule --version
molecule 3.3.4 using python 3.8
    ansible:2.11.1
    azure:0.5.0 from molecule_azure
    containers:0.2.1 from molecule_containers
    delegated:3.3.4 from molecule
    docker:0.2.4 from molecule_docker
    ec2:0.3 from molecule_ec2
    gce:0.2 from molecule_gce
    hetznercloud:1.2.1 from molecule_hetznercloud
    libvirt:0.0.4 from molecule_libvirt
    lxd:0.2 from molecule_lxd
    openstack:0.3 from molecule_openstack
    podman:0.3.0 from molecule_podman
    vagrant:0.6.3 from molecule_vagrant

Anyone please help me debug this?

**Comment by cindyteng** [comment]
Hello @ssbarnea , @decentral1se , @nervo , @abtreece , @dingus9, @brianhelba , @mego22, @ragingpastry, @aminvakil .
Sorry for mentioning you guys in this topic.
I would like to hear some comments from regarding this question.

I am a beginner level on docker and intermediate in ansible.
I am using molecule test for a year now.
I would love to hear comments (anything, good or bad, for my improvement) from you awesome guys who initiate this innovative solution. ^^

**Comment by nervo** [comment]
Hello @cindyteng 

stop spamming, thanks :)

**Comment by aminvakil** [comment]
> I would love to hear comments (anything, good or bad, for my improvement) from you awesome guys who initiate this innovative solution. ^^

I give you two.
Stop asking questions where you're not supposed to do.
Ask questions where you're supposed to do.

**Comment by ssbarnea** [comment]
Best place to use for questions related to molecule is https://github.com/ansible-community/molecule/discussions

**Comment by cindyteng** [comment]
Sorry for spamming. (bow)
Thank you for quick feedback. ^^
I will transfer this to discussion.
