### ISSUE TITLE
pytest command not found

### ISSUE THREAD

**Issue by rholmboe** [ansible-community/toolset#163]
Steps to reproduce:

```bash
$ docker run --rm -it quay.io/ansible/toolset:latest which pytest || echo $?
1
```

It makes jenkins sad when running testinfra/pytest verifier.

**Comment by fletort** [comment]
Why this MR is not accepeted ? Maybe it is to force us to use ansible on verify step ?
In this case, maybe you should list on the readme page what is supported by default or not on the docker image. 
It will be easier to know what we have to install during the prepare step on the given toolset image.

**Comment by fletort** [comment]
@rholmboe your MR is not complete, you must add pytest-molecule and also testinfra.

**Comment by rholmboe** [comment]
> @rholmboe your MR is not complete, you must add pytest-molecule and also testinfra.

This is the issue, not the merge request which you can find here: #164
In the MR, I've included `pytest-molecule` package, which solves this issue to my knowledge.

But since this isn't merged, I've setup my own image based on toolset with my modifications applied.

**Comment by ssbarnea** [comment]
Toolset project was superceeded by https://github.com/ansible/creator-ee
