### ISSUE TITLE
junipernetworks networking modules python requirements missing

### ISSUE THREAD

**Issue by i4o** [ansible-community/toolset#168]
Feel free to ignore this issue, if you didn't mean to run all those included collections without additional pip commands, but just in case.

You are including collections for junipernetworks in your toolset, but modules inside collection have additional python dependencies:

* ncclient (>=v0.6.4) ... almost all juniper modules
* jxmlease  ... junos_command
* junos-eznc ... junos_package, junos_scp 
* xmltodict (>=0.12) ... junos_static_route

**Comment by ssbarnea** [comment]
Inclusion of collections that are not directly needed by molecule is outside of scope of this container. Still, if you need extra collections you can either install the at runtime by documenting them inside `requirements.yml` of your tested codebase or build another container on top of our.
