### ISSUE TITLE
Force ansible color

### ISSUE THREAD

**Issue by nervo** [ansible-community/toolset#18]
Right now, ansible colors are disabled when running playbooks like converge.yml, verify.yml, ...

Please, set `ANSIBLE_FORCE_COLOR` to `1` in Dockerfile :)

**Comment by ssbarnea** [comment]
I am sure sooner or later someone will raise the opposite bug around this but if they want to disable ANSI, they better define it themselves.

**Comment by nervo** [comment]
@ssbarnea for this one, i saw that colors are forced on molecule docker image. As this image is supposed to replace it, i guessed colors must be forced too :)
