### ISSUE TITLE
Provide docker binary

### ISSUE THREAD

**Issue by nervo** [ansible-community/toolset#19]
To use docker driver, docker binary should be available inside the image.

Right now, running molecule playbooks leads to:
```
--> Action: 'converge'

PLAY [Converge] ****************************************************************

TASK [Gathering Facts] *********************************************************
fatal: [debian.buster]: FAILED! => {"msg": "docker command not found in PATH"}

PLAY RECAP *********************************************************************
debian.buster              : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by EricSchatz** [comment]
I seem to have the same problem 

default:
  - create
  - converge
--> Scenario: 'default'
--> Action: 'create'
--> Sanity checks: 'docker'
.....
.....
  File "/usr/local/lib/python3.8/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

**Comment by nervo** [comment]
@EricSchatz you don't have docker socket as docker volume
```
--volume /var/run/docker.sock:/var/run/docker.sock
```

**Comment by EricSchatz** [comment]
> @EricSchatz you don't have docker socket as docker volume
> 
> ```
> --volume /var/run/docker.sock:/var/run/docker.sock
> ```
Thank you ! Now I get a PermissionError: [Errno 13] Permission denied. Docker is running on RHEL 7 with SELinux.  

`$ ls -al | grep docker.sock
srw-rw----.  1 root           root              0 Oct  6 14:15 docker.sock
`
Is there a documentation for the usage of the toolset container ? I'm pretty new to work with containers and don't want to spam this thread.

**Comment by nervo** [comment]
For docker socket & selinux, i guess google is your friend :)

**Comment by ssbarnea** [comment]
I was aware of this limitation but did not care much because the only feature that is broken is "molecule login" option. Still, we better make our users happy.

**Comment by nervo** [comment]
@ssbarnea by `PS`, you mean `PR` ?

**Comment by ssbarnea** [comment]
yeah :)

**Comment by nervo** [comment]
Ah, i think i get it right here https://github.com/ansible-community/toolset/blob/main/Dockerfile#L10
You try to install "docker" package, the real package on debian is "docker.io"
See: https://packages.debian.org/buster/docker
And: https://packages.debian.org/buster/docker.io
