### ISSUE TITLE
There is no podman or docker installed in container

### ISSUE THREAD

**Issue by dakky** [ansible-community/toolset#63]
I used the latest image on quay.io.

when running the container, there is no podman or docker binary available:

```
❯ podman run -dt  ansible/toolset:latest bash
3ba8dcc94dff175aa7d9a92a2e07d8ae26b8a3f2212b1110d6c48b82b736ad93
❯ podman attach -l
root@3ba8dcc94dff:/# podman
bash: podman: command not found
root@3ba8dcc94dff:/# docker 
bash: docker: command not found
root@3ba8dcc94dff:/# dpkg -l | grep podman
root@3ba8dcc94dff:/# dpkg -l | grep docker
ii  docker                    1.5-2                       all          transitional package 
## which is the wrong package
```

there is an mismatch between the content of Dockerfile and the real container.

**Comment by dakky** [comment]
I investigated a little bit deeper:

I tried to build the image myself. The resulting image is nearly double the size compared to the one on quay.io:

```
❯ podman images
REPOSITORY                 TAG              IMAGE ID      CREATED             SIZE   
localhost/toolset          testing          c62b48cdf082  About a minute ago  1.15 GB
quay.io/ansible/toolset    latest           bc5e029e3132  6 weeks ago         693 MB
```

and when running it:

```
❯ podman run -dt localhost/toolset:testing  bash
6435e68b765340958ea630b6a122338370f314ab23ad5821c8a36fcc2bca9121
❯ podman ps
CONTAINER ID  IMAGE                      COMMAND  CREATED         STATUS            PORTS   NAMES
6435e68b7653  localhost/toolset:testing  bash     14 seconds ago  Up 7 seconds ago          flamboyant_gauss
❯ podman attach -l
root@6435e68b7653:/# podman --version
podman version 2.2.1
root@6435e68b7653:/#
```

so this proves:
the build itself is fine an has the correct content. The image on quay is completely broken (outdated?). 
So the mirroing/upload is broken.

**Comment by dakky** [comment]
And another update: seems obvious?

https://github.com/ansible-community/toolset/actions?query=workflow%3Amirror

the mirror job fails always

**Comment by rossedman** [comment]
@dakky It looks like the repo was moved to start using a `main` branch. If you [here](https://quay.io/repository/ansible/toolset?tab=tags), it seems `latest` is broken but the `main` tag is up to date. This worked for me

**Comment by nervo** [comment]
@dakky have a look on https://github.com/ansible-community/toolset/pull/25

**Comment by dakky** [comment]
@rossedman I'll have a look. thanks for that workaround. This issue should be fixed nevertheless.

@nervo jep this was an issue, but here the problem is the broken sync from dockerhub to quay

**Comment by ssbarnea** [comment]
Closing as  `docker run -dit quay.io/ansible/toolset:main bash` works fine and I removed the latest tag.
