### ISSUE TITLE
Add Molecule Hetnzer Cloud plugin?

### ISSUE THREAD

**Issue by decentral1se** [ansible-community/toolset#67]
I guess in the same vein as https://github.com/ansible-community/toolset/issues/61, I'd like to see https://github.com/ansible-community/molecule-hetznercloud included in this image for my own organisations testing. Not sure on the scope of this image but here we go anyway :wave:

**Comment by ssbarnea** [comment]
This image includes actively maintained drivers, so if you want to add it just make a PR and assure that the driver has the requirements installed. 

The only missing drivers were ones that were not compatible with latest molecule or had installation issues.

I will close the ticket to keep the backlog clear, but mentioning again: PR to add it is welcomed.
